### ISSUE TITLE
Increase the "Requires at least" to 6.2

### ISSUE THREAD

**Issue by carolinan** [jonathanbossenger/sendig#2]
The current minimum WordPress version for the theme is 5.8.
The theme cannot be activated on 5.8 because it is missing an index.php file.

The requirement to include the index.php file was removed in WordPress 6.0. But setting the version to 6.2 allows the theme to use the latest features.

**Comment by jonathanbossenger** [comment]
[Fixed here](https://github.com/jonathanbossenger/sendig/commit/6851dd6b09530032637ea5046abe75e94108ac08)
